INFO:     Will watch for changes in these directories: ['C:\\nep\\proyectos\\python\\2025\\liga de futbol\\version13_Qw\\backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [14068] using StatReload
INFO:     Started server process [14972]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:49854 - "GET /api/standings/%7B1%7D HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:63053 - "GET /api/standings/%7B%7D HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:60119 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:60119 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:60119 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:60009 - "GET /api/matches?date=2025-03-23&team_id=89212 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\fastapi\routing.py", line 215, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\starlette\concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2476, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nep\proyectos\python\2025\liga de futbol\version13_Qw\backend\api\matches.py", line 25, in get_matches
    target_date = datetime.strptime(date, "%Y-%m-%d")
                  ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
